apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "capv.fullname" . }}-aggregated-manager-role
  labels:
    cluster.x-k8s.io/provider: infrastructure-vsphere
    cluster.x-k8s.io/v1beta1: v1beta1
  {{- include "capv.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      capv.infrastucture.cluster.x-k8s.io/aggregate-to-manager: "true"
rules: []